# Generated by Django 4.2.16 on 2025-03-09 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DivisionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division_name', models.CharField(max_length=255)),
                ('drm_name', models.CharField(max_length=255)),
                ('zone_name', models.CharField(max_length=255)),
                ('zone_code', models.CharField(max_length=50)),
                ('no_of_divisions', models.IntegerField()),
                ('no_of_stations', models.IntegerField()),
                ('headquarters', models.CharField(max_length=255)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GovtBuilding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=15)),
                ('website', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RailwayDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(max_length=255)),
                ('division_name', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SDAHaryana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=255)),
                ('officer_name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('headquarter', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('epbx_no', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SDAPunjab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('responsibilities', models.TextField()),
            ],
        ),
    ]
